# Generated by Django 4.1.7 on 2023-03-30 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area_no', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_limit', models.IntegerField()),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.BooleanField(default=True)),
                ('doc', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.BooleanField(default=True)),
            ],
        ),
    ]
