# Generated by Django 4.1.7 on 2023-03-30 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=200)),
                ('parking_area_no', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=200)),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.BooleanField(default=True)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.BooleanField(default=True)),
            ],
        ),
    ]
